version: "3"
services: 
    node-app: 
        build: 
            args: 
                NODE_ENV: development
        environment: 
            - NODE_ENV=development
        command: 
            npm run dev
        volumes: 
            - ./:/app:ro
            - /app/node_modules