version: "3"
services: 
    node-app: 
        build: 
            args: 
                NODE_ENV: production
        environment: 
            - NODE_ENV=production
        command: 
            node app.js
            # OR you can type 'npm run start'